// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALyag7wTnTdRDtCWjmH8JBQnYGG7-Nz0k',
    appId: '1:303441382037:web:be542cbf25cd8df183a99c',
    messagingSenderId: '303441382037',
    projectId: 'smart-guru-581fc',
    authDomain: 'smart-guru-581fc.firebaseapp.com',
    storageBucket: 'smart-guru-581fc.appspot.com',
    measurementId: 'G-X6B6QNWS8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOk3E9dEKr3yv3-gct0boeDsl4yb6Ebk',
    appId: '1:303441382037:android:a8483b7c90d32fcd83a99c',
    messagingSenderId: '303441382037',
    projectId: 'smart-guru-581fc',
    storageBucket: 'smart-guru-581fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN9eCmw3MSogV1rvdVFKzgwqPEGN-IhBM',
    appId: '1:303441382037:ios:1c161348f0e8014183a99c',
    messagingSenderId: '303441382037',
    projectId: 'smart-guru-581fc',
    storageBucket: 'smart-guru-581fc.appspot.com',
    iosClientId: '303441382037-lk5smmg880k22a14k1dlub2hdilfk3mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartGuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN9eCmw3MSogV1rvdVFKzgwqPEGN-IhBM',
    appId: '1:303441382037:ios:1c161348f0e8014183a99c',
    messagingSenderId: '303441382037',
    projectId: 'smart-guru-581fc',
    storageBucket: 'smart-guru-581fc.appspot.com',
    iosClientId: '303441382037-lk5smmg880k22a14k1dlub2hdilfk3mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartGuru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALyag7wTnTdRDtCWjmH8JBQnYGG7-Nz0k',
    appId: '1:303441382037:web:944cc8c4b459535883a99c',
    messagingSenderId: '303441382037',
    projectId: 'smart-guru-581fc',
    authDomain: 'smart-guru-581fc.firebaseapp.com',
    storageBucket: 'smart-guru-581fc.appspot.com',
    measurementId: 'G-7PQWSGDD7C',
  );
}
